spring:
  application:
    name: redis-lab
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
  datasource:
    url: jdbc:h2:mem:redislab
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

app:
  rate-limit:
    fixed-window-seconds: 5
    max-requests: 3

logging:
  level:
    org.springframework.data.redis: INFO

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/redis
    driver-class-name: org.postgresql.Driver
    username: redis
    password: redis
