spring:
  application:
    name: mongodb-cdc-kafka-pipeline
  data:
    mongodb:
      uri: mongodb://localhost:27017/cdc_lab?replicaSet=rs0
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    consumer:
      group-id: cdc-lab-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  pipeline:
    topic: order-events
    partition-count: 3
    consumer-concurrency: 3

logging:
  level:
    root: INFO
